services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: exam1234
      POSTGRES_USER: examuser
      POSTGRES_DB: vnuid
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vnuid_network
  
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"  # Cổng AMQP cho Celery
  #     - "15672:15672"  # Cổng Web UI quản lý RabbitMQ
  #   environment:
  #     RABBITMQ_DEFAULT_USER: user
  #     RABBITMQ_DEFAULT_PASS: password
  #   networks:
  #   - vnuid_network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
    - "6379:6379"
    command: ["redis-server"]
    networks:
    - vnuid_network

  vnuid_identity: 
    image: 19122002/vnuid-identity:latest
    container_name: vnuid-identity
    environment:
      DATABASE_URL: postgres://examuser:exam1234@postgres:5432/vnuid?sslmode=disable
      GOOGLE_CLIENT_ID: 842014203560-5h2ec7sni2ag0v1u8v3gm4hn851qo8ur.apps.googleusercontent.com
      JWT_TOKEN: your-secret-key
      JWT_TOKEN_2FA: your-secret-key
      RD_HOST: redis://redis:6379
      RD_DB: 1
      PORT: 4444
    networks:
    - vnuid_network
    depends_on:
      - postgres
      - redis

  vnuid_management: 
    image: 19122002/vnuid-management:latest
    container_name: vnuid-management
    ports:
      - "3000"
    environment:
      DATABASE_URL: postgres://examuser:exam1234@postgres:5432/vnuid?sslmode=disable
      REDIS_URL: redis://redis:6379
      AMQP: amqp://localhost
      INTERNAL_KEY: iNt3rnAl
    networks:
    - vnuid_network
    depends_on:
      - postgres
      - redis

  # vnuid_cdn: 
  #   image: vnuid-identity:latest
  #   container_name: vnuid-identity
  #   ports:
  #     - "3333:3333"
  #   environment:
  #     DATABASE_URL: postgres://examuser:exam1234@postgres:5432/vnuid?sslmode=disable
  #   networks:
  #   - vnuid_network
  #   depends_on:
  #     - postgres

  # vnuid_client: 
  #   image: vnuid-identity:latest
  #   container_name: vnuid-identity
  #   ports:
  #     - "3333:3333"
  #   environment:
  #     DATABASE_URL: postgres://examuser:exam1234@postgres:5432/vnuid?sslmode=disable
  #   networks:
  #   - vnuid_network
  #   depends_on:
  #     - postgres
  
  vnuid_gateway:
    image: 19122002/vnuid-gateway:latest
    container_name: vnuid-gateway
    ports:
      - "1234:80"
    networks:
    - vnuid_network
    depends_on:
      - postgres
      - redis
      - vnuid_identity

volumes:
  postgres_data:
  cdn_data:

networks:
  vnuid_network:
    driver: bridge